Proposal: Remove limits on number of objectives for Threshold SLIs
OpenSLO/OpenSLO pull request #280
Opened 2024-09-04 13:23 UTC by aaranmcguire

I asked in the Slack channel about where multiple objectives should apply for ratio metrics, as I wasn't sure how it could apply to Ratio but not to Threshold. Someone mentioned that they have an Objective for their internal SLO and another for the external SLA.

However, this should surely apply to Threshold metrics too, or even allow something like the following:

SLI: Kafka Topic lag  
Error Budget Method: Timeslice

- Objective 1: 95% of the time, lag should be less than 5 minutes  
- Objective 2: 99% of the time, lag should be less than 10 minutes  

This should be done with the following objectives:

```yaml
objective:
    - displayName: Lag less than 5 minutes 95% of the time
      op: lt
      value: 300
      target: 0.95
    - displayName: Lag less than 10 minutes 99% of the time
      op: lt
      value: 600
      target: 0.99
```

---

Note: As this is not a schema change, I believe we can just remove the comment and allow this for the current spec (rather than delaying it for v2alpha).

2024-09-04 13:28 UTC, fpiwowarczyk approved these changes
I don't know any good reason why we shouldn't have multiple thresholds. Some parts of the spec decisions were made by users that are no longer active maintainers so we may never know why it was set like that. 

LGTM

2024-09-04 13:47 UTC, nieomylnieja requested changes
I think we should delay this to v2alpha.

>  As this is not a schema change, I believe we can just remove the comment and allow this for the current spec

I don't agree with that, the README.md is de facto OpenSLO schema, it's the source of truth, at least until the Go definitions are fully developed.

The whole reason for versioning is to not introduce breaking changes to the schema and if someone has implemented a solution based on that constraint we shouldn't force them to adapt withing v1 version.

I think we all agree with the change itself, so I'd propose to move these changes to [the working document for v2alpha](https://github.com/OpenSLO/OpenSLO/blob/main/enhancements/v2alpha1.md).

2024-09-04 14:10 UTC, aaranmcguire commented
Fair enough, I'll update the PR and just make it add a comment to the v2alpha.

Ideally when we come to write the text in the new v2alpha/v2 spec we can use MUST/SHOULD and other RFC keywords so it's clear when things are recommended or mandated.

2024-10-02 17:22 UTC, fourstepper commented
I would be for dropping that requirement even in v1. I think it is a non-breaking change.

2024-10-09 17:12 UTC, nieomylnieja approved these changes

2024-10-09 17:12 UTC, merged